### ISSUE TITLE
SSL error

### ISSUE THREAD

**Issue by iceplayer112** [rand-net/khan-dl#16] opened 2021-04-18 01:22 UTC
Hi - I'm getting this error:

File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/youtube_dl/YoutubeDL.py", line 598, in trouble
    raise DownloadError(message, exc_info)
youtube_dl.utils.DownloadError: ERROR: Unable to download API page: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1123)> (caused by URLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1123)')))

**Comment by rand-net** [comment] 2021-05-03 19:49
Duplicate of #7

**Comment by iceplayer112** [comment] 2021-05-03 20:54
I tried this khan-dl -c https://www.khanacademy.org/test-prep/mcat/
youtube-dl --no-check-certificate and it doesnt work still :( am i doing it
wrong? appreciate the help
-Ryan

Ryan Witt | C: (818) 800-8659 | https://www.linkedin.com/in/ryanjwitt

**Comment by rand-net** [comment] 2021-05-26 19:40
`khan-dl -c https://www.khanacademy.org/test-prep/mcat/ youtube-dl --no-check-certificate`  won't work.

You can either check for proxy misconfiguration or certificates are missing.  It might be also due to censorship.
For more information, check this https://stackoverflow.com/questions/51785882/youtube-dl-gave-me-an-error-about-ssl

**Comment by rand-net** [comment] 2021-05-26 19:40
`khan-dl -c https://www.khanacademy.org/test-prep/mcat/ youtube-dl --no-check-certificate`  won't work.

You can either check for proxy misconfiguration or certificates are missing.  It might be also due to censorship.
For more information, check this https://stackoverflow.com/questions/51785882/youtube-dl-gave-me-an-error-about-ssl

**Closed** 2021-05-26 19:40 UTC
